# -*- coding: utf-8 -*-
"""Day02-PythonStandardIOPractices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Io6dBKinpPD7NunwCv1bJRMJWqZrDrgN

# Day 02 Python Standard IO Assisted Practices

IO Stream stands for Input and Output Stream. Here we will primarily focus on Standard Input (stdin) and Standard output (stdout) Stream

## BEST PROGRAMMING PRACTICE

> **1: Python String Format -** Using Python String Format in Print function enhances the readability and maintainability of the code

> **2: Naming Conventions -**
- **Global or Local Variables -** Should be in lower case and Use an underscore to join words.
- **Constants in Python -** Should be only in upper case and Use an underscore to join words.
- **Function Names -** Should be in lower case and Use an underscore to join words.
- **Module Names -** Should be in lower case and Use an underscore to join words.
- **Package Names -** Should be in lower case and Use an underscore to join words.
- **Class Names -** Should follow CapWords convention.
- **Merhod Names -** Should be in lower case and Use an underscore to join words.
- **Merhod Arguments -**
  - Every instance method should have ‘self’ as its first argument.
  - Class methods should have their first argument named ‘cls’.

> **3: Descriptive Variable Name -**
- Avoid names that are too general or wordy. Maintain a good balance between the two.
- **Bad:** user_list, dict_to_store_defns_of_a_word, swapNums, moveInts.
- **Good:** user_info, word_definitions, swap_numbers, move_integers.
- Avoid naming things like “X”, “Y” or “Z”.
- Capitalize all letters of an abbreviation when using camelcase.
- Avoid names starting with digits. Combination of lowercase letters (a to z) or uppercase letters (A to Z) or digits (0 to 9) or an underscore (_) can be used.

> **4: Hard Coding Variables -** Hardcoding values to variables within your code can create maintenance and scalability challenging.

> **5: Embracing Modularization -** Writing monolithic scripts without breaking code into reusable functions or classes can make code difficult to test, debug, and maintain.

> **6: Proper Function Usage -** Python Functions are block of code that is run only when called. Guidelines for Python functions
- 1: Proper Comments for the function
- 2: Use of Global Variable should be avoided
- 3: Use of function type annotation, by Default is any

> **7: Handling Exceptions -** Ignoring exceptions or using bare except: clauses can hide bugs and lead to unexpected failures. Be specific about the exceptions you catch and handle, improving debugging and error resolution.

> **8: Unit Test Cases -** Unit tests are designed to test single units of code in isolation. They are quick and easy to create, and help find and fix bugs early in the development cycle.
- In Unit Test Cases the Input and the Output are well defined. It is to ensure the program also gives the same output
- Please ensure all the Unit Test Cases identified in the program are tested

## PROG 1: OOPS Banner

Write a Program to output OOPS as a Banner using 9 characters and 9 Rows of space and astrix

> **Input =>** NONE

> **Output =>**

```
   ***         ***      ******         *****
 **   **     **   **    **    **     **      
**     **   **     **   **     **   **       
**     **   **     **   **    **     **      
**     **   **     **   ******         ***   
**     **   **     **   **                **
**     **   **     **   **                 **
 **   **     **   **    **                **
   ***         ***      **           *****   
```
> **Hint =>**
1. Use print function with 9 Characters of Space `' '` or `'*'` for each letter i.e. O, O, P, S
2. Use 9 Print Statements
"""

# PROG 2: OOPS Banner
print("   ***         ***      ******         *****")
print(" **   **     **   **    **    **     **     ")
print("**     **   **     **   **     **   **      ")
print("**     **   **     **   **    **     **     ")
print("**     **   **     **   ******         ***  ")
print("**     **   **     **   **                **")
print("**     **   **     **   **                 **")
print(" **   **     **   **    **                ** ")
print("   ***         ***      **           *****   ")
# Write The Code Here

"""## PROG 2: Places to visit

Write a program is take user name and the 3 places to visit in the year from the user and display as the following

> **Purpose -** The purpose of this program is the use of seperator and end parameters of `print()` function

> **Input =>** Narayan, Mumbai, Pune, Chennai, 2024

> **Output =>** `Hello Narayan and places to visit Mumbai, Pune, Chennai in the Year 2024`

> **Hint =>**
1. Use of `print(value, ..., sep=',', end=' ')` function with `sep=','` and `end = ' '`
2. Use of Python Formatted String Literal (f-String)

"""

# PROG 2: Places to visit
name = input()
place1 = input()
place2 = input()
place3 = input()
year = input()

print("Hello", name, "and places to visit", end=" ")
print(place1, place2, place3, sep=",", end=" ")
print("in the Year", year)
# Write The Code Here

"""## PROG 3: Compute Circumference and Area of Circle

Write a Program to Compute Circumference and Area of a Circle in cm and cm<sup>2</sup> by taking the radius (r) of a circle in inch as a input

> **Input =>** Radius of the Circle in Inch. For e.g. 5

> **Output =>** Circumference of the Circle is 31.42 cm and Area of the Cricle is 78.57 sqcm

> **Hint =>**
- 1: Convert Inch to CM using 1 inch = 2.54 centimeters
- 2: Perimeter of a circle is 2πr and Area of Circle is πr<sup>2</sup>
- 3: Use Constant PI as in `PI = 22/7`
- 4: Use `**` Operator to compute radius<sup>2</sup> as in `area = PI * (radius ** 2)`
- 5: Note: `(radius ** 2)` is enclosed in bracket indicating that radius<sup>2</sup> need to be computed first and then multiplied with PI. This is part of **Operator Precedence**

### PROG 3.1: Compute Circumference and Area of Circle
"""

# PROG 3.1: Compute Circumference and Area of Circle
radius_inch = float(input("Enter the radius of the circle in inches: "))
radius_cm = radius_inch * 2.54

PI = 22 / 7

circumference = 2 * PI * radius_cm

area = PI * (radius_cm ** 2)

print(f"Circumference of the Circle is {circumference} cm and Area of the Circle is {area} sqcm")
# Write The Code Here

"""### PROG 3.2: Compute with Python Format Specifier"""

# PROG 3.2: Compute Circumference and Area of Circle with
# Python Format Specifier for floating-point number
radius_inch = float(input("Enter the radius of the circle in inches: "))
radius_cm = radius_inch * 2.54

PI = 22 / 7

circumference = 2 * PI * radius_cm

area = PI * (radius_cm ** 2)

print(f"Circumference of the Circle is {circumference:.2f} cm and Area of the Circle is {area:.2f} sqcm")
# Write The Code Here

"""## PROG 4: Find Generation

Write a Program to take birth year as input and find the generation the user belongs.

> **Input =>** Enter Birth Year for e.g. 1970

> **Output =>**
```
Birth Year is 1970
Is Baby Boomer: False
Is Gen X: True
Is Millennial: False
Is Gen Z: False
Is Gen Alpha: False

> **Hint =>**
- 1: Python Shorthand If Else
- 2: The Generation is based on the year as shown below  
Baby Boomers: Born 1946-1964.
<br>Generation X: Born 1965-1980.
<br>Millennials: Born 1981-1996.
<br>Generation Z: Born 1997-2012.
<br>Generation Alpha: Born 2013-2025.

"""

# PROG 4: Find Generation
year = int(input("Enter Birth Year: "))

is_boomer = 1946 <= year <= 1964
is_genx = 1965 <= year <= 1980
is_millennial = 1981 <= year <= 1996
is_genz = 1997 <= year <= 2012
is_alpha = 2013 <= year <= 2025

print("Birth Year is", year)
print("Is Baby Boomer:", is_boomer)
print("Is Gen X:", is_genx)
print("Is Millennial:", is_millennial)
print("Is Gen Z:", is_genz)
print("Is Gen Alpha:", is_alpha)
# Write The Code Here

"""## PROG 5: Time Conversion

Take input of time duration for an activity in seconds. Convert the same seconds in hours , minutes and seconds. Print in HH:MM:SS format.

> **Input =>** Enter Number of Seconds for e.g. 3800

> **Output =>** `Time duration of 3800 seconds in HH:MM:SS format is 01:03:20`

> **Hint =>**
1. Use 1 hour = 3600 seconds
2. Use Floor Division Operator `//` and Modulo `%`
3. In the code `hour = 3800 // 3600` results in 1 hour
4. In the code `minutes = (3800 % 3600) // 60` results on 3 minutes
5. In the code `seconds = 3800 % 60` results in 20 seconds
6. Print the Result HH:MM:SS format. For this we use  Python String Format Specifier for Integers `:02d` to put leading zeors if it is a single digit number. For e.g. 1 is represented as 01
"""

# PROG 5: Time Conversion
seconds = int(input("Enter the time duration in seconds: "))

hours = seconds // 3600
minutes = (seconds % 3600) // 60
secs = seconds % 60

print("Time duration of", seconds, "seconds in HH:MM:SS format is",
      f"{hours:02d}:{minutes:02d}:{secs:02d}")
# Write The Code Here

"""## PROG 6: Bill Generation App

A wholesale fruit seller wants to compute the total amount of money he would like to bill a customer. He sells Apples and Oranges. Since Apples are imported they attract a higher GST of 12% compared to Oranges which are procurred locally hence have a GST of 5%.

For bill generation, the seller needs to capture the buyer name, price at which the seller is selling the apple and oranges for the quantity purchased by the buyer.

> **Input and Output =>** Refer the sample below

```
Enter Buyer Name: Narayan
Enter Apple price per kg: 200
Enter Apple Quantity in kg: 10
Enter Orange price per kg: 150
Enter Orange Quantity in kg: 10

Buyer Name: Narayan
--------------------------------------------------------------------------------
| Item Code  | Price/Unit |  # unit  |   Price    |    GST     | Total w/ GST |
--------------------------------------------------------------------------------
|   Apple    |   Rs 200   |   10.0   | Rs 2000.0  |  Rs 240.0  |  Rs 2240.0   |
|   Orange   |   Rs 150   |   10.0   | Rs 1500.0  |  Rs 75.0   |  Rs 1575.0   |
--------------------------------------------------------------------------------
Total                                                              ₹ 3815.00
Total Round                                                        ₹ 3815.00
--------------------------------------------------------------------------------

```



"""

## Prog 6: Bill Generation App
name = input("Enter Buyer Name: ")
apple_price = float(input("Enter Apple price per kg: "))
apple_qty = float(input("Enter Apple Quantity in kg: "))
orange_price = float(input("Enter Orange price per kg: "))
orange_qty = float(input("Enter Orange Quantity in kg: "))

apple_gst_rate = 0.12
orange_gst_rate = 0.05

apple_total = apple_price * apple_qty
apple_gst = apple_total * apple_gst_rate
apple_final = apple_total + apple_gst

orange_total = orange_price * orange_qty
orange_gst = orange_total * orange_gst_rate
orange_final = orange_total + orange_gst

grand_total = apple_final + orange_final

print("\nBuyer Name:", name)
print("-" * 74)

print(f"| {'Item Code':^10} | {'Price/Unit':^10} | {'# unit':^6} | {'Price':^10} | {'GST':^10} | {'Total w/ GST':^12} |")
print("-" * 74)

print(f"| {'Apple':^10} | Rs {apple_price:<6.0f} | {apple_qty:<6.1f} | Rs {apple_total:<7.1f} | Rs {apple_gst:<7.1f} | Rs {apple_final:<9.1f} |")
print(f"| {'Orange':^10} | Rs {orange_price:<6.0f} | {orange_qty:<6.1f} | Rs {orange_total:<7.1f} | Rs {orange_gst:<7.1f} | Rs {orange_final:<9.1f} |")

print("-" * 74)

print(f"{'Total':<60} ₹ {grand_total:.2f}")
print(f"{'Total Round':<60} ₹ {round(grand_total):.2f}")

print("-" * 74)
# Write The Code Here

"""## PROG 7: School Report App

**School Result:** For a school - “New School Of Learning '', create a program where individual results of each student of the class XI are generated and also a summary of the class is created.  

Get 3 student names
For each student, get physics, chemistry and mathematics marks  out of 50.
Publish the results on screen for all of the  students . Result should have School name, Student name and Class Name in the heading.

Then in tabular manner print subject, marks obtained, % of marks
Also total marks obtained and total percentage at the end of table.

For school summary - generate class average of each subject and overall average

> **Output =>**

```
Enter name of student 1: Narayan
Enter Physics marks out of 50 for student 1: 35
Enter Chemistry marks out of 50 for student 1: 45
Enter Mathematics marks out of 50 for student 1: 30

New School Of Learning - Class XI - Narayan
------------------------------------------------------------------------
|     Subject     |   Total Marks   | Marks Obtained  |   Percentage    |
------------------------------------------------------------------------
|     Physics     |       50        |       35        |      70.0       |
|    Chemistry    |       50        |       45        |      90.0       |
|   Mathematics   |       50        |       30        |      60.0       |
------------------------------------------------------------------------
|      Total      |       150       |       110       |      73.33      |
------------------------------------------------------------------------


Enter name of student 2: Karthik
Enter Physics marks out of 50 for student 2: 40
Enter Chemistry marks out of 50 for student 2: 40
Enter Mathematics marks out of 50 for student 2: 45

New School Of Learning - Class XI - Karthik
------------------------------------------------------------------------
|     Subject     |   Total Marks   | Marks Obtained  |   Percentage    |
------------------------------------------------------------------------
|     Physics     |       50        |       40        |      80.0       |
|    Chemistry    |       50        |       40        |      80.0       |
|   Mathematics   |       50        |       45        |      90.0       |
------------------------------------------------------------------------
|      Total      |       150       |       125       |      83.33      |
------------------------------------------------------------------------


Enter name of student 3: Vidya
Enter Physics marks out of 50 for student 3: 40
Enter Chemistry marks out of 50 for student 3: 45
Enter Mathematics marks out of 50 for student 3: 40

New School Of Learning - Class XI - Vidya
------------------------------------------------------------------------
|     Subject     |   Total Marks   | Marks Obtained  |   Percentage    |
------------------------------------------------------------------------
|     Physics     |       50        |       40        |      80.0       |
|    Chemistry    |       50        |       45        |      90.0       |
|   Mathematics   |       50        |       40        |      80.0       |
------------------------------------------------------------------------
|      Total      |       150       |       125       |      83.33      |
------------------------------------------------------------------------



Class Average And Percentage for Each Subject:
Physics Average is 38.33 and Percentage is 76.67%
Chemistry Average is 43.33 and Percentage is 86.67%
Mathematics Average is 38.33 and Percentage is 76.67%
Overall Percentage: 80.00%
```

**CODIN STEPS**

> **Step 1: -** Specifying Constants for School, Class, subjects marks, total, and number of students

> **Step 2: -** Get student name, physics, chemistry and maths marks for Student 1 and Calculate total marks for student 1

> **Step 3: -** Calculating physics, chemistry and maths percentage for student 1

> **Step 4: -** Print results for student 1

> **TEST CASE 1: -**

```
Enter name of student 1: Narayan
Enter Physics marks out of 50 for student 1: 35
Enter Chemistry marks out of 50 for student 1: 45
Enter Mathematics marks out of 50 for student 1: 30

New School Of Learning - Class XI - Narayan
------------------------------------------------------------------------
|     Subject     |   Total Marks   | Marks Obtained  |   Percentage    |
------------------------------------------------------------------------
|     Physics     |       50        |       35        |      70.0       |
|    Chemistry    |       50        |       45        |      90.0       |
|   Mathematics   |       50        |       30        |      60.0       |
------------------------------------------------------------------------
|      Total      |       150       |       110       |      73.33      |
------------------------------------------------------------------------

```

> **Step 5: -** Get student name, physics, chemistry and maths marks for Student 2 and Calculate total marks for student 2

> **Step 6: -** Calculating physics, chemistry and maths percentage for student 2

> **Step 7: -** Print results for student 2

> **TEST CASE 2: -**

```

Enter name of student 2: Karthik
Enter Physics marks out of 50 for student 2: 40
Enter Chemistry marks out of 50 for student 2: 40
Enter Mathematics marks out of 50 for student 2: 45

New School Of Learning - Class XI - Karthik
------------------------------------------------------------------------
|     Subject     |   Total Marks   | Marks Obtained  |   Percentage    |
------------------------------------------------------------------------
|     Physics     |       50        |       40        |      80.0       |
|    Chemistry    |       50        |       40        |      80.0       |
|   Mathematics   |       50        |       45        |      90.0       |
------------------------------------------------------------------------
|      Total      |       150       |       125       |      83.33      |
------------------------------------------------------------------------


```

> **Step 8: -** Get student name, physics, chemistry and maths marks for Student 3 and Calculate total marks for student 3

> **Step 9: -** Calculating physics, chemistry and maths percentage for student 3

> **Step 10: -** Print results for student 3

> **TEST CASE 3: -**

```

Enter name of student 3: Vidya
Enter Physics marks out of 50 for student 3: 40
Enter Chemistry marks out of 50 for student 3: 45
Enter Mathematics marks out of 50 for student 3: 40

New School Of Learning - Class XI - Vidya
------------------------------------------------------------------------
|     Subject     |   Total Marks   | Marks Obtained  |   Percentage    |
------------------------------------------------------------------------
|     Physics     |       50        |       40        |      80.0       |
|    Chemistry    |       50        |       45        |      90.0       |
|   Mathematics   |       50        |       40        |      80.0       |
------------------------------------------------------------------------
|      Total      |       150       |       125       |      83.33      |
------------------------------------------------------------------------

```

> **Step 11: -** Calculate total marks obtained by all students in each subject

> **Step 12: -** Calculate class averages for each subject

> **Step 13: -** Calculate the class average percentage for each subject

> **Step 14: -** Calculate total marks obtained by all students

> **Step 15: -** Calculate overall percentage

> **Step 16: -** Print the class average percentage for each subject

> **FINAL OUTPUT: -**

```
Class Average And Percentage for Each Subject:
Physics Average is 38.33 and Percentage is 76.67%
Chemistry Average is 43.33 and Percentage is 86.67%
Mathematics Average is 38.33 and Percentage is 76.67%
Overall Percentage: 80.00%

```
"""

# PROG 7: School Report App
SCHOOL = "New School Of Learning"
CLASS = "Class XI"
TOTAL_MARKS = 50

phy_total = chem_total = math_total = 0
overall_total = 0

for i in range(1, 4):
    name = input(f"Enter name of student {i}: ")
    phy = int(input(f"Enter Physics marks out of 50 for student {i}: "))
    chem = int(input(f"Enter Chemistry marks out of 50 for student {i}: "))
    math = int(input(f"Enter Mathematics marks out of 50 for student {i}: "))

    total = phy + chem + math
    percentage = total / 150 * 100

    phy_total += phy
    chem_total += chem
    math_total += math
    overall_total += total

    print(f"\n{SCHOOL} - {CLASS} - {name}")
    print("-" * 60)
    print(f"| {'Subject':^12} | {'Total Marks':^12} | {'Marks Obtained':^15} | {'Percentage':^10} |")
    print("-" * 60)

    print(f"| {'Physics':^12} | {TOTAL_MARKS:^12} | {phy:^15} | {phy/50*100:^10.1f} |")
    print(f"| {'Chemistry':^12} | {TOTAL_MARKS:^12} | {chem:^15} | {chem/50*100:^10.1f} |")
    print(f"| {'Mathematics':^12} | {TOTAL_MARKS:^12} | {math:^15} | {math/50*100:^10.1f} |")

    print("-" * 60)
    print(f"| {'Total':^12} | {150:^12} | {total:^15} | {percentage:^10.2f} |")
    print("-" * 60)

phy_avg = phy_total / 3
chem_avg = chem_total / 3
math_avg = math_total / 3

phy_per = phy_avg / 50 * 100
chem_per = chem_avg / 50 * 100
math_per = math_avg / 50 * 100

overall_per = overall_total / (3 * 150) * 100

print("\nClass Average And Percentage for Each Subject:")
print(f"Physics Average is {phy_avg:.2f} and Percentage is {phy_per:.2f}%")
print(f"Chemistry Average is {chem_avg:.2f} and Percentage is {chem_per:.2f}%")
print(f"Mathematics Average is {math_avg:.2f} and Percentage is {math_per:.2f}%")
print(f"Overall Percentage: {overall_per:.2f}%")43
# Write The Code Here

"""# Day 02 Python Standard IO Cheet Sheet

**CODIN CONCEPTS**

> **1: Standard IO (stdio) -** stdio stands for Standard Input and Output.

> **2: Formatted string literal, or f-string -**
- An **f-string** looks very much like a typical Python string except that it’s prepended by the character `f''` or `F''`
- The magic of f-strings is that you can embed Python expressions directly inside them by using curly braces `{}`.
- The expression is evaluated and converted to string representation, and the result is interpolated into the original string in that location

> **3: Python Data Types -** Data types define the kind of data that can be stored in memory for a variable. In Python Data Types are implicitly assigned. For Python all built-in data types belongs to Python class. They can be categorized as either
- **Primitive Data Types -** int, float, str, bool
- **Derived Data Types -** list, dict, set, tuple

- **4: Python Explicit Type Conversion -** Type conversion is converting from one data type to another. Explicit type conversion is achieved through Python's built-in functions such as `int()`, `float()`, and `str()`.

> **5: Python Constant -** Constants are types of variables whose values cannot be altered or changed after initialization. These values are universally proven to be true and they cannot be changed over time. e.g. `PI = 22/7`
- Naming Convention to define Constant is all caps
- Python constants are declared and initialized in the beginning of the program as global or preferably in different modules/files.

> **6: Python Format Specifier -**
- Formatting float variables as string with Format Specifier expression like `{number:.2f}`.
- Formatting integer variables as string with Format Specifier expression like `{number:02d}`.

> **7: Python Operator -** Operators are special symbols that perform operations on variables and values. They are
1. Arithmetic Operators like Add is `+`, Subtract is `-`, Multiply is `*`, Power is `**`...
2. Assignment Operator `=` used in assigning value to a variable
3. Comparison Operator to compare 2 values like `==`, `!=`, `>=` ...
4. Logical Operator used in expression `and`, `or`, and `not`
5. Bitwise operators for bit operations `&`, `|`,...
6. Special Operators for memory comparison like `is` & `is not`

> **8: Python Operator Precedence -** In Python, the order of operations follows the same principles as PEMDAS.
- PEMDAS is an acronym that stands for “Parentheses, Exponents, Multiplication and Division, and Addition and Subtraction”
- That is, expressions inside parentheses are evaluated first, followed by exponents, then multiplication and division (from left to right), and finally addition and subtraction (from left to right).

> **9: Conditional Operation -** The conditional operation simply allows testing a condition in a single line replacing the multiline if-else making the code compact. It predominantly uses Comparison Operator and Logical Operators

> **10: Python Shorthand If Else -** If you have only one condition to execute, one for if, and one for else, you can put it all on the same line using Python Shorthand as in `gender == 'male' and 'his' or 'her'`
- **Comparison Operator -** Please note the use of Comparison Operator `==` to check the gender is 'male'

> **11: String Formatting Expression -** We use the followimg String formatting expressions
1. `{'Item Code':^10}` is a string formatting expression used to center-align the text "Item Code" within a field width of 10 characters. Here's what each part of the expression means:
2. `{'-' * 74}` is used to repeat the character `'-'` 74 times. This is because of the multiplier operator `*`
3. `{' ' * 54}` is used to repeat space character `' '` 54 times due to operator `*`

# Day 02 Python Standard IO Self Practices

## PROG 1: Print 3 Names

Write a program that takes three names as input and prints out Hi to friends with the names in the reverse of the order given. For example, it gives "Hi Anthony, Akbar and Amar.".

> **Input =>** Amar, Akbar, Anthony

> **Output =>** Hi Anthony, Akbar and Amar.
"""

# PROG 1: Print 3 Names

# Write The Code Here

"""## PROG 2: Favorite Places

Get the input of 5 places you would like to visit . Print these places with a comma and a space in between the places. Also print the Five Places with a Gap of 2 Lines

> **Input =>** Srinagar, Jabalpur, Jaisalmer, Chidambaram, Shillong

> **Output # 1 =>** My Favorite Places are Srinagar, Jabalpur, Jaisalmer, Chidambaram, Shillong

> **Output # 2 =>**
My Favorite Places are
<br>Srinagar
<br><br>Jabalpur
<br><br>Jaisalmer
<br><br>Chidambaram
<br><br>Shillong

> **Hint =>**
1. For Output 1 and 2 try with using print function parameter `sep = ', '` and sep = `'\n\n'`
2. For Output 2 try with using print function parameter `end = '\n\n'`
3. The String '\n' indicates New Line
"""

PROG 2: Favorite Places

# Write The Code Here

"""## PROG 3: Name Banner

Write a Program to output your name as a Banner using 9 characters and 9 Rows of space and astrix. Similat to OOPS Banner program already solved in Assisted Practice For e.g. for OOPS

> **Input =>** NONE

> **Output =>**

```
   ***         ***      ******         *****
 **   **     **   **    **    **     **      
**     **   **     **   **     **   **       
**     **   **     **   **    **     **      
**     **   **     **   ******         ***   
**     **   **     **   **                **
**     **   **     **   **                 **
 **   **     **   **    **                **
   ***         ***      **           *****   
```
> **Hint =>**
1. Use print function with 9 Characters of Space `' '` or `'*'` for each letter like the one demonstrated for OOPS i.e. O, O, P, S
2. Use 9 Print Statements


"""

PROG 3: Name Banner

# Write The Code Here

"""## PROG 4: Formatted String Literal

Get the name and place of stay of your friend. Based on name determine his or her place of stay. Print the same in following sentence using formatted string concept:
Name of my friend is <name> and his/her place of stay is  <place>.

> **Input =>** Narayan, Mumbai

> **Output =>** `Name of my friend is Narayan and his/her place of stay is Mumbai.`

> **Hint =>**
1. Use of Python Formatted String Literal (f-String)

"""

# PROG 4: Formatted String Literal

# Write The Code Here

"""## PROG 5: Compute Square Root

Write a Program to calculate the square root of a Number.

> **Input =>** Enter a Number. For e.g. 4

> **Output =>** `The square root of 4.00 is 2.00`

> **Hint =>**
1. Square Root of a Number is number<sup>0.5</sup> using `number ** 0.5`
2. Print the Square Root with 2 decimal places using Python Format Specifier for floating-point number

"""

# PROG 5: Compute Square Root

# Write The Code Here

"""## PROG 6: Temperature_Conversion

Write a Program to take the temperature in Celsius  as input and compute and print the temperature in Fahrenheit using the formula `fahrenheit = (celsius * 9/5) + 32`

> **Input =>** Enter celsius. For e.g. 35

> **Output =>** `Temperature in Fahrenheit is 95.0 for Celsius 35.0`

> **Hint =>**
1. Use code `fahrenheit = (celsius * 9/5) + 32` for conversion
2. Print the Result with 1 decimal places using Python Format Specifier for floating-point number

"""

# PROG 6: Temperature_Conversion

# Write The Code Here

"""## PROG 7: Perimeter and Area of a Rectangle

Write a Program to compute and print perimeter and area of a rectangle in inch and inch<sup>2</sup>,  where length and breadth are entered in cm.

> **Input =>** Enter length and breadth in centimeters. eg 20 and 30

> **Output =>** `Perimeter of the rectangle is 39.37 inches and Area of the rectangle: 93.00 square inches`

> **Hint =>**
1. Use 1 inch = 2.54 centimeters
2. Perimeter = 2 * (length + breadth) and area = length * breadth
2. Print the Result with 2 decimal places using Python Format Specifier for floating-point number

"""

# PROG 7: Perimeter and Area of a Rectangle

# Write The Code Here

"""## PROG 8: Retail Invoicing App

A  retail shop-keeper wants to compute the total amount of money he would like to bill to a customer. He  has two types of items : household goods and processed food items.  Household goods have a GST of 5% and processed food items have a GST of 12%..

For Retail Invoicing, the seller needs to capture the buyer name, price at which the seller is selling the Household goods and processed food along with the quantity purchased by the buyer.

> **Input and Outout =>** Refer Below the sample

> **Hint =>** Refer Assisted Practice PROG 7
- Print the final amount with Indian Rupee Symbol (Use unicode)

```
Enter Buyer Name: Narayan
Enter Household Good Price: 350
Enter Household Good Quantity: 5
Enter Processed Food price: 125
Enter Processed Food Quantity: 10

Buyer Name: Narayan
----------------------------------------------------------------------------------
|    Item Code    | Price/Unit | #unit |   Price    |    GST     | Total w/ GST |
----------------------------------------------------------------------------------
| Household Good  |   Rs 350   |  5.0  | Rs 1750.0  |  Rs 87.5   |  Rs 1837.5   |
| Processed Food  |   Rs 125   | 10.0  | Rs 1250.0  |  Rs 150.0  |  Rs 1400.0   |
----------------------------------------------------------------------------------
Total                                                                ₹ 3237.50
Total Round                                                          ₹ 3238.00
----------------------------------------------------------------------------------

```


"""

# PROG 8: Retail Invoicing App

# Write The Code Here